# site settings
title: SMH
subtitle: by Sarah M-H
email: smosshorwitz@gmail.com
description: UX, Design and Dev Projects
baseurl: "/sarahmh
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
github_url: https://gitlab.com/smosshor
instagram_url: https://instagram.com/sarahmoho
linkedin_url: https://www.linkedin.com/in/sarahmh

# build settings
markdown: kramdown

sass:
  style: compressed
